### ISSUE TITLE
Open-source Somo-RL

### ISSUE THREAD

**Issue by DongChen06** [GrauleM/somogym#1]
Dear authors, thanks for the wonderful paper and repo, do you plan to make the codes for training and evaluating RL algorithms open-source recently? Thank you!

**Comment by GrauleM** [comment]
Thanks! Yes, actively working on some clean-up! Will be public by the time we present our work at ICRA in Philadelphia (end of May 2022).

**Comment by Derekabc** [comment]
Hi @GrauleM, Looking forward to the key updates!

**Comment by lilanpei** [comment]
@GrauleM Looking forward too for any updates, would appreciate any pointers, thank you.

**Comment by GrauleM** [comment]
finally pushed a first release of somo-rl (linked in the readme). unfortunately, at this point I cannot give any guarantees for completeness, as I did not have time for careful testing.
